### ISSUE TITLE
    Rendering SLS 'base:nfs.server' failed: Jinja variable 'dict object' has no attribute 'service_server_dependency'

### ISSUE THREAD

**Issue by syphernl** [saltstack-formulas/nfs-formula#13]
Using this on an Ubuntu 14.04 minion (Salt 2015.8.5) results in a critical error:

```
[INFO    ] Fetching file from saltenv 'base', ** done ** u'nfs/server.sls'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'nfs/map.jinja'
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'service_server_dependency'
[CRITICAL] Rendering SLS 'base:nfs.server' failed: Jinja variable 'dict object' has no attribute 'service_server_dependency'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:nfs.server' failed: Jinja variable 'dict object' has no attribute 'service_server_dependency'
```

**Comment by wwentland** [comment]
This is being caused by #12 which breaks deployment if `service_server_dependency` is not set. Try setting that to `False` in your pillar as a workaround.

**Comment by syphernl** [comment]
Yeah I figured that out as well :-) With that, it does work (well should but apparently you cannot setup NFS in an LXC container :()

**Comment by micron** [comment]
I ran into the same issue. Setting `service_server_dependency: False` works as an workaround.

**Comment by 0xf10e** [comment]
Aw, crap… sorry, folks, I totally missed this issue :(
Got to manage my GitHub subscriptions better so I don't miss the relevant bits…

**Comment by javierbertoli** [comment]
This issue is ~2yr old, and the formula does not even have the parameter `service_server_dependency` anymore, so I'm closing this issue.
